### ISSUE TITLE
Allow using local vcpkg

### ISSUE THREAD

**Issue by kem0x** [build-cpp/cmkr#119]
As the title implies, there's no option to use locally installed vcpkg, instead of reinstalling vcpkg in every project.

**Comment by ZehMatt** [comment]
This ensures that everyone is on the same version and I believe this is intentional.

**Comment by kem0x** [comment]
> This ensures that everyone is on the same version and I believe this is intentional.

this should be optional as it's really inconvenient with mutliple projects, lets say im using LLVM while i already have it compiled on my local vcpkg clone why would i have to compile for another 8 hours everytime i create a project that uses llvm with cmkr?

**Comment by mrexodia** [comment]
You should just use find-package directly in that case and set the right CMAKE_PREFIX_PATH.

**Comment by kem0x** [comment]
i still believe it's redundant and disk consuming to have the same vcpkg packages installed in every project too 🤷‍♂️
