### ISSUE TITLE
Could you give me admin access?

### ISSUE THREAD

**Issue by mrexodia** [build-cpp/cmkr#14]
@MoAlyousef could you give me admin access to this repository so I can manage the settings?

**Comment by MoAlyousef** [comment]
I would but apparently since this isn't an organization, there is no such option.

**Comment by MoAlyousef** [comment]
If you would like, I can transfer the ownership of this repo, you'll have to delete your fork first I think.

**Comment by mrexodia** [comment]
Perhaps it would be better to create a new organization (any name suggestions?) instead and have us both be admins there

**Comment by mrexodia** [comment]
Maybe https://github.com/build-cpp (cpp-build is also available). Then the website could be https://build-cpp.github.io(/cmkr)

**Comment by mrexodia** [comment]
Awesome, thanks!
