### ISSUE TITLE
Upgrade cmkr to C++17/20 ?

### ISSUE THREAD

**Issue by Guekka** [build-cpp/cmkr#30]
Hey. I've stumbled upon this repo and find the concept very interesting. I may give it a try on some of my projects

But I'm wondering, why use C++11? Some parts of the code could be made more modern using a more recent version of C++. Is there any reason to keep an old version?

**Comment by mrexodia** [comment]
Hello,

Thanks for your interest! Using C++11 is indeed on purpose and I wrote my design considerations in more detail at https://github.com/build-cpp/cmkr/pull/2.

The gist of it is that C++11 is pretty much universally supported now (even on older distros, weird in-house systems etc.) so using C++11 means that the bootstrapping process can always complete. Perhaps in ~5 years the major version can be bumped when C++14 becomes universally supported.

I think it would be helpful to write down design considerations like this in a page of the documentation, so I’ll try to get to that whenever I have time :)

**Comment by Guekka** [comment]
I understand your point, but cmkr is a binary, not a library. And as far as I know, CMake only supports Windows, Mac and Linux. So distributing Windows, Mac and Linux binaries should be enough to achieve compatibility with every system.

Anyway, it's your choice, I can understand it. Thanks for the quick answer. As for:
 > I think it would be helpful to write down design considerations like this in a page of the documentation

I think linking that issue in the readme would be good enough for now

**Comment by mrexodia** [comment]
True, the releases on GitHub are already shipping independent binaries, but
running untrusted binaries downloaded from the internet is not always an
option.

In the default mode cmkr ships a bootstrapping module that automatically
downloads the exact version of cmkr and compiles it during your
configuration process (optionally from your own git servers). This means
you can audit and fully trust the whole pipeline vs having to trust a
“random” binary from the internet.

Personally I would also prefer a more modern C++, but when setting that as
a requirement you are excluding a large chunk of the potential userbase
just to save a few lines of code. To me there is no substantial upside,
while the potential downside is huge.

**Comment by Guekka** [comment]
I did not consider security. I still think there are alternatives for someone wanting a trusted binary (build on a trusted recent system, share the binary). But I understand better, thanks for explaining.
