### ISSUE TITLE
[feature] Add an 'SET' option

### ISSUE THREAD

**Issue by gmh5225** [build-cpp/cmkr#57]
Now I want to use `set(CMAKE_GENERATOR_TOOLSET, "llvm-msvc")`.
But I didn't find a way to use it in the cmkr project.
Is it possible to consider adding a `SET = ["CMAKE_GENERATOR_TOOLSET"="llvm-msvc"]`

**Comment by mrexodia** [comment]
This is not something that should be part of your CMake project. Instead you use `cmake -B build -T ClangCL` to build with the LLVM toolset.

**Comment by gmh5225** [comment]
> This is not something that should be part of your CMake project. Instead you use `cmake -B build -T ClangCL` to build with the LLVM toolset.

I see. Thank you.
