### ISSUE TITLE
Add an example for WDK

### ISSUE THREAD

**Issue by mrexodia** [build-cpp/cmkr#58]
Example: https://github.com/build-cpp/cmkr/blob/bcbc9d2b20827322b4248772156f347356e62514/tests/driver/cmake.toml

**Comment by cpkt9762** [comment]
//cmake/FindWdk.cmake
cmake-before="""list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/cmake")"""
[find-package]
WDK = {}
[target.drv]
link-libraries = ["WDK"] 
///

**Comment by cpkt9762** [comment]
wdk

**Comment by mrexodia** [comment]
A template is available here: https://github.com/build-cpp/wdk_template
