### ISSUE TITLE
[feature] Add 'type = "msvc-static"'

### ISSUE THREAD

**Issue by gmh5225** [build-cpp/cmkr#63]
There are times when we want to use `/MT` instead of `/MD`
The following code can do this by replacing `/MD` with `/MT`
```Cmake
# Enable static msvc runtime.
if (MSVC)
    set(CompilerFlags
        CMAKE_CXX_FLAGS
        CMAKE_CXX_FLAGS_DEBUG
        CMAKE_CXX_FLAGS_RELEASE
        CMAKE_CXX_FLAGS_MINSIZEREL
        CMAKE_CXX_FLAGS_RELWITHDEBINFO
        CMAKE_C_FLAGS
        CMAKE_C_FLAGS_DEBUG
        CMAKE_C_FLAGS_RELEASE
        CMAKE_C_FLAGS_MINSIZEREL
        CMAKE_C_FLAGS_RELWITHDEBINFO
        )
    foreach(CompilerFlag ${CompilerFlags})
        string(REPLACE "/MD" "/MT" ${CompilerFlag} "${${CompilerFlag}}")
        string(REPLACE "/MDd" "/MTd" ${CompilerFlag} "${${CompilerFlag}}")
        set(${CompilerFlag} "${${CompilerFlag}}" CACHE STRING "msvc compiler flags" FORCE)
        message("MSVC flags: ${CompilerFlag}:${${CompilerFlag}}")
    endforeach()
endif(MSVC)
```
But it's too much trouble to copy and paste every time
If possible, add an `msvc-static` type, it would be much easier :)
```
[target.hello_world]
type = "msvc-static"
sources = ["src/main.cpp"]
```

**Comment by mrexodia** [comment]
Doing it this way is super incorrect. You should use https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html (and enable the relevant policy) instead.

Still might be nice to build into cmkr though.

**Comment by gmh5225** [comment]
I see. Thank you for your reply.
Because `set_property(TARGET foo PROPERTY MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")` 
does not work well in Z3 project.
![image](https://user-images.githubusercontent.com/13917777/191804278-083577e9-2c1e-4ae8-99a5-029f46fad287.png)
The replacement method works well.

**Comment by mrexodia** [comment]
Yeah you need to enable https://cmake.org/cmake/help/latest/policy/CMP0091.html#policy:CMP0091 before the `project()` call otherwise it does nothing

**Comment by gmh5225** [comment]
My bad. Looks like my version of cmake is too old.
Thank you for your reply.
`set_property(TARGET foo PROPERTY MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")` works well.
